
package usuariows.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuarioServiceWS", targetNamespace = "http://web.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioServiceWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns usuariows.cliente.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarUsuarioPorId", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.BuscarUsuarioPorId")
    @ResponseWrapper(localName = "buscarUsuarioPorIdResponse", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.BuscarUsuarioPorIdResponse")
    @Action(input = "http://web.com.sv/UsuarioServiceWS/buscarUsuarioPorIdRequest", output = "http://web.com.sv/UsuarioServiceWS/buscarUsuarioPorIdResponse")
    public Usuario buscarUsuarioPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.ActualizarUsuarioResponse")
    @Action(input = "http://web.com.sv/UsuarioServiceWS/actualizarUsuarioRequest", output = "http://web.com.sv/UsuarioServiceWS/actualizarUsuarioResponse")
    public void actualizarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "inhabilitarUsuario", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.InhabilitarUsuario")
    @ResponseWrapper(localName = "inhabilitarUsuarioResponse", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.InhabilitarUsuarioResponse")
    @Action(input = "http://web.com.sv/UsuarioServiceWS/inhabilitarUsuarioRequest", output = "http://web.com.sv/UsuarioServiceWS/inhabilitarUsuarioResponse")
    public void inhabilitarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<usuariows.cliente.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.ListarUsuariosResponse")
    @Action(input = "http://web.com.sv/UsuarioServiceWS/listarUsuariosRequest", output = "http://web.com.sv/UsuarioServiceWS/listarUsuariosResponse")
    public List<Usuario> listarUsuarios();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertarUsuario", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.InsertarUsuario")
    @ResponseWrapper(localName = "insertarUsuarioResponse", targetNamespace = "http://web.com.sv/", className = "usuariows.cliente.InsertarUsuarioResponse")
    @Action(input = "http://web.com.sv/UsuarioServiceWS/insertarUsuarioRequest", output = "http://web.com.sv/UsuarioServiceWS/insertarUsuarioResponse")
    public void insertarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0);

}
