
package ingresows.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IngresoServiceImplService", targetNamespace = "http://servicio.com.sv/", wsdlLocation = "http://localhost:9090/IngresoServiceImplService/IngresoServiceImpl?wsdl")
public class IngresoServiceImplService
    extends Service
{

    private final static URL INGRESOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException INGRESOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName INGRESOSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.com.sv/", "IngresoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/IngresoServiceImplService/IngresoServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INGRESOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        INGRESOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IngresoServiceImplService() {
        super(__getWsdlLocation(), INGRESOSERVICEIMPLSERVICE_QNAME);
    }

    public IngresoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INGRESOSERVICEIMPLSERVICE_QNAME, features);
    }

    public IngresoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, INGRESOSERVICEIMPLSERVICE_QNAME);
    }

    public IngresoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INGRESOSERVICEIMPLSERVICE_QNAME, features);
    }

    public IngresoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IngresoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IngresoServiceWS
     */
    @WebEndpoint(name = "IngresoServiceImplPort")
    public IngresoServiceWS getIngresoServiceImplPort() {
        return super.getPort(new QName("http://servicio.com.sv/", "IngresoServiceImplPort"), IngresoServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IngresoServiceWS
     */
    @WebEndpoint(name = "IngresoServiceImplPort")
    public IngresoServiceWS getIngresoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.com.sv/", "IngresoServiceImplPort"), IngresoServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INGRESOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw INGRESOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return INGRESOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
