
package ingresows.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IngresoServiceWS", targetNamespace = "http://web.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IngresoServiceWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "inhabilitarIngreso", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.InhabilitarIngreso")
    @ResponseWrapper(localName = "inhabilitarIngresoResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.InhabilitarIngresoResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/inhabilitarIngresoRequest", output = "http://web.com.sv/IngresoServiceWS/inhabilitarIngresoResponse")
    public void inhabilitarIngreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarIngreso", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ActualizarIngreso")
    @ResponseWrapper(localName = "actualizarIngresoResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ActualizarIngresoResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/actualizarIngresoRequest", output = "http://web.com.sv/IngresoServiceWS/actualizarIngresoResponse")
    public void actualizarIngreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Ingreso arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ingresows.cliente.Ingreso>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarTop10Ingresos", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ListarTop10Ingresos")
    @ResponseWrapper(localName = "listarTop10IngresosResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ListarTop10IngresosResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/listarTop10IngresosRequest", output = "http://web.com.sv/IngresoServiceWS/listarTop10IngresosResponse")
    public List<Ingreso> listarTop10Ingresos();

    /**
     * 
     * @param arg0
     * @return
     *     returns ingresows.cliente.Ingreso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarIngresoPorId", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarIngresoPorId")
    @ResponseWrapper(localName = "buscarIngresoPorIdResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarIngresoPorIdResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/buscarIngresoPorIdRequest", output = "http://web.com.sv/IngresoServiceWS/buscarIngresoPorIdResponse")
    public Ingreso buscarIngresoPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ingresows.cliente.Cuenta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCuentaPorNumeroCuenta", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarCuentaPorNumeroCuenta")
    @ResponseWrapper(localName = "buscarCuentaPorNumeroCuentaResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarCuentaPorNumeroCuentaResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/buscarCuentaPorNumeroCuentaRequest", output = "http://web.com.sv/IngresoServiceWS/buscarCuentaPorNumeroCuentaResponse")
    public Cuenta buscarCuentaPorNumeroCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ingresows.cliente.Cuenta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCuentaPorId", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarCuentaPorId")
    @ResponseWrapper(localName = "buscarCuentaPorIdResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.BuscarCuentaPorIdResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/buscarCuentaPorIdRequest", output = "http://web.com.sv/IngresoServiceWS/buscarCuentaPorIdResponse")
    public Cuenta buscarCuentaPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @throws IngresoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "agregarIngreso", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.AgregarIngreso")
    @ResponseWrapper(localName = "agregarIngresoResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.AgregarIngresoResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/agregarIngresoRequest", output = "http://web.com.sv/IngresoServiceWS/agregarIngresoResponse", fault = {
        @FaultAction(className = IngresoException_Exception.class, value = "http://web.com.sv/IngresoServiceWS/agregarIngreso/Fault/IngresoException")
    })
    public void agregarIngreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Ingreso arg0)
        throws IngresoException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarCuenta", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ActualizarCuenta")
    @ResponseWrapper(localName = "actualizarCuentaResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ActualizarCuentaResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/actualizarCuentaRequest", output = "http://web.com.sv/IngresoServiceWS/actualizarCuentaResponse")
    public void actualizarCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Cuenta arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ingresows.cliente.Ingreso>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarIngresos", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ListarIngresos")
    @ResponseWrapper(localName = "listarIngresosResponse", targetNamespace = "http://web.com.sv/", className = "ingresows.cliente.ListarIngresosResponse")
    @Action(input = "http://web.com.sv/IngresoServiceWS/listarIngresosRequest", output = "http://web.com.sv/IngresoServiceWS/listarIngresosResponse")
    public List<Ingreso> listarIngresos();

}
