
package ingresows.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IngresoException", targetNamespace = "http://web.com.sv/")
public class IngresoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IngresoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IngresoException_Exception(String message, IngresoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IngresoException_Exception(String message, IngresoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ingresows.cliente.IngresoException
     */
    public IngresoException getFaultInfo() {
        return faultInfo;
    }

}
