
package egresows.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CuentaException", targetNamespace = "http://web.com.sv/")
public class CuentaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CuentaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CuentaException_Exception(String message, CuentaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CuentaException_Exception(String message, CuentaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: egresows.cliente.CuentaException
     */
    public CuentaException getFaultInfo() {
        return faultInfo;
    }

}
