
package egresows.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EgresoServiceWS", targetNamespace = "http://web.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EgresoServiceWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "inhabilitarEgreso", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.InhabilitarEgreso")
    @ResponseWrapper(localName = "inhabilitarEgresoResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.InhabilitarEgresoResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/inhabilitarEgresoRequest", output = "http://web.com.sv/EgresoServiceWS/inhabilitarEgresoResponse")
    public void inhabilitarEgreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns egresows.cliente.Egreso
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarEgresoPorId", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.BuscarEgresoPorId")
    @ResponseWrapper(localName = "buscarEgresoPorIdResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.BuscarEgresoPorIdResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/buscarEgresoPorIdRequest", output = "http://web.com.sv/EgresoServiceWS/buscarEgresoPorIdResponse")
    public Egreso buscarEgresoPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns egresows.cliente.Cuenta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCuentaPorId", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.BuscarCuentaPorId")
    @ResponseWrapper(localName = "buscarCuentaPorIdResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.BuscarCuentaPorIdResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/buscarCuentaPorIdRequest", output = "http://web.com.sv/EgresoServiceWS/buscarCuentaPorIdResponse")
    public Cuenta buscarCuentaPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @throws EgresoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "agregarEgreso", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.AgregarEgreso")
    @ResponseWrapper(localName = "agregarEgresoResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.AgregarEgresoResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/agregarEgresoRequest", output = "http://web.com.sv/EgresoServiceWS/agregarEgresoResponse", fault = {
        @FaultAction(className = EgresoException_Exception.class, value = "http://web.com.sv/EgresoServiceWS/agregarEgreso/Fault/EgresoException")
    })
    public void agregarEgreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Egreso arg0)
        throws EgresoException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<egresows.cliente.Egreso>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEgresos", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ListarEgresos")
    @ResponseWrapper(localName = "listarEgresosResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ListarEgresosResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/listarEgresosRequest", output = "http://web.com.sv/EgresoServiceWS/listarEgresosResponse")
    public List<Egreso> listarEgresos();

    /**
     * 
     * @param arg0
     * @throws CuentaException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarCuenta", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ActualizarCuenta")
    @ResponseWrapper(localName = "actualizarCuentaResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ActualizarCuentaResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/actualizarCuentaRequest", output = "http://web.com.sv/EgresoServiceWS/actualizarCuentaResponse", fault = {
        @FaultAction(className = CuentaException_Exception.class, value = "http://web.com.sv/EgresoServiceWS/actualizarCuenta/Fault/CuentaException")
    })
    public void actualizarCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Cuenta arg0)
        throws CuentaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws EgresoException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarEgreso", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ActualizarEgreso")
    @ResponseWrapper(localName = "actualizarEgresoResponse", targetNamespace = "http://web.com.sv/", className = "egresows.cliente.ActualizarEgresoResponse")
    @Action(input = "http://web.com.sv/EgresoServiceWS/actualizarEgresoRequest", output = "http://web.com.sv/EgresoServiceWS/actualizarEgresoResponse", fault = {
        @FaultAction(className = EgresoException_Exception.class, value = "http://web.com.sv/EgresoServiceWS/actualizarEgreso/Fault/EgresoException")
    })
    public void actualizarEgreso(
        @WebParam(name = "arg0", targetNamespace = "")
        Egreso arg0)
        throws EgresoException_Exception
    ;

}
