
package cuentaws.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CuentaServiceWS", targetNamespace = "http://web.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CuentaServiceWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns cuentaws.cliente.Cuenta
     * @throws CuentaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCuentaPorNumeroCuenta", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarCuentaPorNumeroCuenta")
    @ResponseWrapper(localName = "buscarCuentaPorNumeroCuentaResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarCuentaPorNumeroCuentaResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/buscarCuentaPorNumeroCuentaRequest", output = "http://web.com.sv/CuentaServiceWS/buscarCuentaPorNumeroCuentaResponse", fault = {
        @FaultAction(className = CuentaException_Exception.class, value = "http://web.com.sv/CuentaServiceWS/buscarCuentaPorNumeroCuenta/Fault/CuentaException")
    })
    public Cuenta buscarCuentaPorNumeroCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws CuentaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns cuentaws.cliente.Cuenta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarCuentaPorId", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarCuentaPorId")
    @ResponseWrapper(localName = "buscarCuentaPorIdResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarCuentaPorIdResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/buscarCuentaPorIdRequest", output = "http://web.com.sv/CuentaServiceWS/buscarCuentaPorIdResponse")
    public Cuenta buscarCuentaPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cuentaws.cliente.Login
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarLoginPorId", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarLoginPorId")
    @ResponseWrapper(localName = "buscarLoginPorIdResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.BuscarLoginPorIdResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/buscarLoginPorIdRequest", output = "http://web.com.sv/CuentaServiceWS/buscarLoginPorIdResponse")
    public Login buscarLoginPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @throws CuentaException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarCuenta", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.ActualizarCuenta")
    @ResponseWrapper(localName = "actualizarCuentaResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.ActualizarCuentaResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/actualizarCuentaRequest", output = "http://web.com.sv/CuentaServiceWS/actualizarCuentaResponse", fault = {
        @FaultAction(className = CuentaException_Exception.class, value = "http://web.com.sv/CuentaServiceWS/actualizarCuenta/Fault/CuentaException")
    })
    public void actualizarCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Cuenta arg0)
        throws CuentaException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<cuentaws.cliente.Cuenta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCuentas", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.ListarCuentas")
    @ResponseWrapper(localName = "listarCuentasResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.ListarCuentasResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/listarCuentasRequest", output = "http://web.com.sv/CuentaServiceWS/listarCuentasResponse")
    public List<Cuenta> listarCuentas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "agregarCuenta", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.AgregarCuenta")
    @ResponseWrapper(localName = "agregarCuentaResponse", targetNamespace = "http://web.com.sv/", className = "cuentaws.cliente.AgregarCuentaResponse")
    @Action(input = "http://web.com.sv/CuentaServiceWS/agregarCuentaRequest", output = "http://web.com.sv/CuentaServiceWS/agregarCuentaResponse")
    public void agregarCuenta(
        @WebParam(name = "arg0", targetNamespace = "")
        Cuenta arg0);

}
