
package cuentaws.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CuentaServiceImplService", targetNamespace = "http://servicio.com.sv/", wsdlLocation = "http://localhost:9090/CuentaServiceImplService/CuentaServiceImpl?wsdl")
public class CuentaServiceImplService
    extends Service
{

    private final static URL CUENTASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUENTASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CUENTASERVICEIMPLSERVICE_QNAME = new QName("http://servicio.com.sv/", "CuentaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/CuentaServiceImplService/CuentaServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUENTASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CUENTASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CuentaServiceImplService() {
        super(__getWsdlLocation(), CUENTASERVICEIMPLSERVICE_QNAME);
    }

    public CuentaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUENTASERVICEIMPLSERVICE_QNAME, features);
    }

    public CuentaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CUENTASERVICEIMPLSERVICE_QNAME);
    }

    public CuentaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUENTASERVICEIMPLSERVICE_QNAME, features);
    }

    public CuentaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CuentaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CuentaServiceWS
     */
    @WebEndpoint(name = "CuentaServiceImplPort")
    public CuentaServiceWS getCuentaServiceImplPort() {
        return super.getPort(new QName("http://servicio.com.sv/", "CuentaServiceImplPort"), CuentaServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CuentaServiceWS
     */
    @WebEndpoint(name = "CuentaServiceImplPort")
    public CuentaServiceWS getCuentaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.com.sv/", "CuentaServiceImplPort"), CuentaServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUENTASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CUENTASERVICEIMPLSERVICE_EXCEPTION;
        }
        return CUENTASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
