
package loginws.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginServiceWS", targetNamespace = "http://web.com.sv/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginServiceWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns loginws.cliente.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarUsuarioPorId", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.BuscarUsuarioPorId")
    @ResponseWrapper(localName = "buscarUsuarioPorIdResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.BuscarUsuarioPorIdResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/buscarUsuarioPorIdRequest", output = "http://web.com.sv/LoginServiceWS/buscarUsuarioPorIdResponse")
    public Usuario buscarUsuarioPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "actualizarLogin", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.ActualizarLogin")
    @ResponseWrapper(localName = "actualizarLoginResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.ActualizarLoginResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/actualizarLoginRequest", output = "http://web.com.sv/LoginServiceWS/actualizarLoginResponse")
    public void actualizarLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        Login arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns loginws.cliente.Login
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarLoginPorId", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.BuscarLoginPorId")
    @ResponseWrapper(localName = "buscarLoginPorIdResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.BuscarLoginPorIdResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/buscarLoginPorIdRequest", output = "http://web.com.sv/LoginServiceWS/buscarLoginPorIdResponse")
    public Login buscarLoginPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertarLogin", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.InsertarLogin")
    @ResponseWrapper(localName = "insertarLoginResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.InsertarLoginResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/insertarLoginRequest", output = "http://web.com.sv/LoginServiceWS/insertarLoginResponse")
    public void insertarLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        Login arg0);

    /**
     * 
     * @return
     *     returns java.util.List<loginws.cliente.Login>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLogin", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.ListarLogin")
    @ResponseWrapper(localName = "listarLoginResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.ListarLoginResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/listarLoginRequest", output = "http://web.com.sv/LoginServiceWS/listarLoginResponse")
    public List<Login> listarLogin();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "inhabilitarLogin", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.InhabilitarLogin")
    @ResponseWrapper(localName = "inhabilitarLoginResponse", targetNamespace = "http://web.com.sv/", className = "loginws.cliente.InhabilitarLoginResponse")
    @Action(input = "http://web.com.sv/LoginServiceWS/inhabilitarLoginRequest", output = "http://web.com.sv/LoginServiceWS/inhabilitarLoginResponse")
    public void inhabilitarLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
