
package loginws.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginServiceImplService", targetNamespace = "http://servicio.com.sv/", wsdlLocation = "http://localhost:9090/LoginServiceImplService/LoginServiceImpl?wsdl")
public class LoginServiceImplService
    extends Service
{

    private final static URL LOGINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOGINSERVICEIMPLSERVICE_QNAME = new QName("http://servicio.com.sv/", "LoginServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/LoginServiceImplService/LoginServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOGINSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LoginServiceImplService() {
        super(__getWsdlLocation(), LOGINSERVICEIMPLSERVICE_QNAME);
    }

    public LoginServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINSERVICEIMPLSERVICE_QNAME, features);
    }

    public LoginServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGINSERVICEIMPLSERVICE_QNAME);
    }

    public LoginServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINSERVICEIMPLSERVICE_QNAME, features);
    }

    public LoginServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginServiceWS
     */
    @WebEndpoint(name = "LoginServiceImplPort")
    public LoginServiceWS getLoginServiceImplPort() {
        return super.getPort(new QName("http://servicio.com.sv/", "LoginServiceImplPort"), LoginServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginServiceWS
     */
    @WebEndpoint(name = "LoginServiceImplPort")
    public LoginServiceWS getLoginServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.com.sv/", "LoginServiceImplPort"), LoginServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOGINSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOGINSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
